# Galapix - an image viewer for large image collections
# Copyright (C) 2015,2016 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Build file for https://travis-ci.org/
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Based on:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# https://github.com/SuperTux/supertux/blob/master/.travis.yml

language: cpp
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

os:
  - linux

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "avCYzv34u0qw4gaPvxHk5mcCFdO8HdSkGzH+9VJ6g3FJaV1y8BMU+KE3CnsgNtrmOS3KL+O10N4bhJEvamid9mfNpv5Mtk4bumU8Q0sCe1guKtEU0FEO8ZAKKz3ooh1f61fBlrNv7ZMOHIhWxpZKH8XBKtpzAcTkG535Zii3rkA="
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-4.0"; fi

  # patch for mhash, see https://bugs.launchpad.net/ubuntu/+source/mhash/+bug/1465562
  # - sudo sed -i "s/_Bool/bool/" /usr/include/mutils/mutils.h

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=OFF -DBUILD_TESTS=ON -DBUILD_EXTRA=ON -DBUILD_GALAPIX_SDL=ON -DBUILD_GALAPIX_GTK=ON
  - make VERBOSE=1
  - (cd .. && build-${BUILD_TYPE}/test_galapix)

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - build-essential
    - libglew-dev
    - libopenal-dev
    - libsqlite3-dev
    - libjsoncpp-dev
    - libgl1-mesa-dev
    - libcurl4-openssl-dev
    - libpng12-dev
    - libjpeg8-dev
    - libmagick++-dev
    - libexif-dev
    - libglademm-2.4-dev
    - libgtkglextmm-x11-1.2-dev
    - libgtkmm-2.4-dev
    - libmhash-dev
    - libboost-filesystem1.55-dev
    - libboost-signals1.55-dev
    - libboost-system1.55-dev
    - g++-4.9
    - clang-4.0

  coverity_scan:
    project:
      name: "Galapix/galapix"
      description: "Build submitted via Travis CI"
    notification_email: grumbel@gmail.com
    build_command_prepend: "cmake . && make clean"
    build_command: "make"
    branch_pattern: coverity_scan

# EOF #
