# Galapix - an image viewer for large image collections
# Copyright (C) 2015 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Build file for https://travis-ci.org/
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Based on:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# https://github.com/SuperTux/supertux/blob/master/.travis.yml

language: cpp

compiler:
  - gcc

matrix:
  fast_finish: true

env:
  global:
    - CMAKE_VERSION=3.2.1 SDL2_VERSION=2.0.3 SDL2IMAGE_VERSION=2.0.0 SDL2MIXER_VERSION=2.0.0
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libglew-dev libopenal-dev libsqlite3-dev libjsoncpp-dev libgl1-mesa-dev libcurl4-openssl-dev libpng12-dev libjpeg8-dev libmagick++-dev libexif-dev libglademm-2.4-dev libgtkglextmm-x11-1.2-dev libgtkmm-2.4-dev libmhash-dev

  # Current gcc that supports C++ 11 features
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

  # boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-filesystem1.55-dev libboost-signals1.55-dev libboost-system1.55-dev

  # CMake
  - wget http://www.cmake.org/files/v3.2/cmake-$CMAKE_VERSION.tar.gz -O - | tar xz
  - (cd cmake-$CMAKE_VERSION && cmake . && make -j3 && sudo make install)

  # build glm
  - wget http://downloads.sourceforge.net/project/ogl-math/glm-0.9.6.3/glm-0.9.6.3.zip
  - unzip glm-0.9.6.3.zip
  - (cd glm && mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install)

  # SDL dependencies
  - wget http://libsdl.org/release/SDL2-$SDL2_VERSION.tar.gz -O - | tar xz
  - (cd SDL2-$SDL2_VERSION && ./configure --prefix=/usr && make -j3 && sudo make install)
  - wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-$SDL2IMAGE_VERSION.tar.gz -O - | tar xz
  - (cd SDL2_image-$SDL2IMAGE_VERSION && ./configure --prefix=/usr && make -j3 && sudo make install)
  - wget http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-$SDL2MIXER_VERSION.tar.gz -O - | tar xz
  - (cd SDL2_mixer-$SDL2MIXER_VERSION && ./configure --prefix=/usr && make -j3 && sudo make install)

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=OFF -DBUILD_TESTS=ON -DBUILD_EXTRA=ON -DBUILD_GALAPIX_SDL=ON -DBUILD_GALAPIX_GTK=ON
  - make VERBOSE=1
  - (cd .. && build-${BUILD_TYPE}/test_galapix)

# EOF #
